# Generated by Django 4.0.6 on 2022-07-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='is_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='is_first',
            field=models.IntegerField(null=True),
        ),
    ]
