# Generated by Django 4.0.6 on 2022-07-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_alter_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
