# Generated by Django 4.0.6 on 2022-07-18 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_alter_user_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='group',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='user',
        ),
    ]
