# Generated by Django 4.0.6 on 2022-07-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_newfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='body',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='is_end',
            field=models.IntegerField(blank=0, null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='is_first',
            field=models.IntegerField(blank=0, null=True),
        ),
    ]
