# Generated by Django 4.0.5 on 2022-07-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_remove_group_body_alter_todolist_is_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='enddate',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='is_end',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='is_first',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
