# Generated by Django 4.0.6 on 2022-07-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_remove_todolist_enddate_alter_todolist_is_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('body', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
