# Generated by Django 4.0.6 on 2022-07-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0012_alter_newfile_myfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='newfile',
            name='body',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='newfile',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
