# Generated by Django 4.0.6 on 2022-07-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0013_newfile_body_newfile_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newfile',
            name='body',
        ),
    ]
