# Generated by Django 4.0.6 on 2022-07-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0015_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newfile',
            name='body',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
